# Generated by Django 4.2.5 on 2023-11-29 07:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('num_habi', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero Habitacion')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('no disponible', 'No Disponible'), ('mantencion', 'En Mantencion')], max_length=30)),
                ('orientacion', models.CharField(choices=[('norte', 'Norte'), ('sur', 'Sur'), ('este', 'Este'), ('oeste', 'Oeste')], max_length=30)),
                ('prec_habi', models.CharField(choices=[('25.000', '$25.000'), ('40.000', '$40.000'), ('75.000', '$75.000')], max_length=30, verbose_name='Precio')),
                ('capacidad', models.CharField(choices=[('2', '2 Personas'), ('4', '4 Personas'), ('6', '6 Personas')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Huespedes',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(12)])),
                ('nombre', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(80)])),
                ('apellidos', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(80)])),
                ('correo', models.EmailField(max_length=254)),
                ('num_telefono', models.CharField(max_length=12, validators=[django.core.validators.MaxLengthValidator(12), django.core.validators.MinLengthValidator(9)], verbose_name='Numero Telefono')),
                ('residencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut_usu', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(12)], verbose_name='Rut')),
                ('nombre', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(80)])),
                ('apellidos', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(80)])),
                ('cargo', models.CharField(choices=[('administrador', 'Administrador'), ('encargado', 'Encargado')], max_length=15)),
                ('password', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('activo', 'Habilitado'), ('inactivo', 'Deshabilitado')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fechaReserva', models.DateTimeField(auto_now_add=True,verbose_name='Fecha Reserva')),
                ('fechaIngreso', models.DateField(verbose_name='Ingreso')),
                ('fechaSalida', models.DateField(verbose_name='Salida')),
                ('num_habi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hdm_App.habitaciones', verbose_name='Numero Habitacion')),
                ('rut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hdm_App.huespedes', verbose_name='Rut Huesped')),
                ('rut_usu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hdm_App.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
