# Generated by Django 4.2.5 on 2023-12-03 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdm_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huespedes',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(12)]),
        ),
    ]
