# Generated by Django 4.2.5 on 2023-11-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdm_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='fechaReserva',
            field=models.DateTimeField(verbose_name='Fecha Reserva'),
        ),
    ]
