# Generated by Django 4.2.5 on 2023-12-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdm_App', '0002_alter_reservas_totalpagar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='totalpagar',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
